### ISSUE TITLE
Page relaod issue

### ISSUE THREAD

**Issue by Laraib-Azmat** [Laraib-Azmat/Dynamic_Travel_Website.github.io#1]
Hello I am facing an issue in my *Dynamic Travel Website* https://github.com/Laraib-Azmat/Dynamic_Travel_Website.github.io/commit/c27bf99dfe0cb3dfeb877ebb9ed722f29ddef008. Its  a  2 page website. When I clicked on the button of first page it opens the second page and  all page transitions and animations works fine. When I reload first page its works fine but when I reload second page the entire JavaScript not worked. Help me to solve it.

**Comment by MRodriguez-M** [comment]
Hi, I'd like to help with this bug, can you assign this to me?

**Comment by nikhilpanchal1** [comment]
> Hello I am facing an issue in my _Dynamic Travel Website_ [c27bf99](https://github.com/Laraib-Azmat/Dynamic_Travel_Website.github.io/commit/c27bf99dfe0cb3dfeb877ebb9ed722f29ddef008). Its a 2 page website. When I clicked on the button of first page it opens the second page and all page transitions and animations works fine. When I reload first page its works fine but when I reload second page the entire JavaScript not worked. Help me to solve it.

Hey there! Just wanted to inform you that I've resolved issue. I've addressed the problem and submitted a PR for review. Would appreciate it if you could take a look at your earliest convenience.

**Comment by ZainEjaz24** [comment]
Hi, I can help you with the issue you mentioned , can you assign this to me?

**Comment by Laraib-Azmat** [comment]
Thank you but its done
